create table loan_account_t (
    ln_acc_id serial primary key,
    cif varchar(20) not null,
    ln_acc_nbr varchar(20) unique not null,
    ln_acc_holder_nm varchar(100) not null,
    acc_typ varchar(20) not null,
    sub_acc_typ varchar(20) not null,
    ln_amt decimal(15,2) not null,
    emi_amt decimal(15,2) not null,
    emi_due_dt date not null,
    ln_trm_yrs int not null,
    int_rate decimal(5,2) not null,
    crdt_score int not null,
    ann_inc decimal(15,2) not null,
    exist_emis int not null,
    emp_typ varchar(20) not null,
    is_active boolean,
    ln_strt_dt date not null,
    ln_end_dt date not null,
    crt_at timestamp,
    crt_by varchar(40),
    updt_at timestamp,
    updt_by varchar(40),
    foreign key (cif) references customer_t(cif)
);